### PR TITLE
re-align download button

### PR DESCRIPTION
**Pull request by Ushie**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Can you please fix this PR?

**Comment by Sculas** [comment]
What did you merge? In `Files changed` it shows nothing, and in `merged commit c418452` it shows the `2.53.0` release commit.

**Comment by oSumAtrIX** [comment]
Actually, i don't know, I didn't merge this PR, it was probably marked as merged and closed due to HEAD being in another PR which was merged.

**Comment by Ushie** [comment]
> Can you please fix this PR?

Yep, will push again in a sec

**Pull request merged**
