### PR TITLE
fix(disable-startup-shorts-player): remove redundant opcodes pattern list

### PR DESCRIPTION
**Pull request by OxrxL**
Closes: https://github.com/revanced/revanced-patches/issues/674

### CODE REVIEW

**Comment by johnconner122** [comment]
Stil fails!

**Comment by OxrxL** [comment]
> Still fails!

Which version?

**Comment by johnconner122** [comment]
YouTube_v17.36.37
image

**Comment by johnconner122** [comment]
Also fails in v17.33.42

**Comment by OxrxL** [comment]
> Also fails in v17.33.42

It works on both version for me.

Did you update CLI and Patcher? Because there is a fix available for them, which make this patch working. Otherwise it always fails.

**Comment by OxrxL** [comment]
> Also fails in v17.33.42

This is the patcher fix I was talking about: https://github.com/revanced/revanced-patcher/commit/843e62ad290ee0a707be9322ee943921da3ea420

**Pull request merged**
