### PR TITLE
fix(YouTube - Spoof client): Fix tracking history on brand accounts

### PR DESCRIPTION
**Pull request by oSumAtrIX**
RE: https://github.com/ReVanced/revanced-integrations/pull/669

### CODE REVIEW

**Comment by n1cKz1** [comment]
I just patched dev and tested briefly, apparently history still isn't tracking for me

**Comment by oSumAtrIX** [comment]
Use a network debugger with the network debugging patch and check if the patch has successfully changed the request urls authority

**Comment by n1cKz1** [comment]
Will do later once I get home.

I do use adguard but the patched app is whitelisted. History tracks fine when spoofing is off.

**Comment by n1cKz1** [comment]
> check if the patch has successfully changed the request urls authority

I tested with spoof client on and off to check for any differences in the traffic and there wasn't any. Double checked that AdGuard isn't at fault, history also works with VR spoofing as expected. 

Luckily for some reason I'm still unaffected by the playback issue so I'll keep spoofing off for now.

**Comment by oSumAtrIX** [comment]
Which authority was present?

**Comment by n1cKz1** [comment]
These are some requests that appear when opening videos with iOS spoofing:

image
image

What am I supposed to look for?

**Comment by oSumAtrIX** [comment]
You are interested in the watch history requests. So those that have api/stats in their path.

**Comment by n1cKz1** [comment]
Spoofing on:
image

Spoofing off:
image

**Pull request merged**
