### PR TITLE
fix: make `custom-branding` cross-platform

### PR DESCRIPTION
**Pull request by ponces**
InputStream.readAllBytes was only introduced [on Android in API 33](https://developer.android.com/reference/java/io/InputStream#readAllBytes()) so we need an implementation for a wider adoption :)

### CODE REVIEW

**Comment by Sculas** [comment]
Could this be made an extension function instead? (in a separate PR, of course)

**Comment by ponces** [comment]
> Could this be made an extension function instead? (in a separate PR, of course)

You mean all this code, including `getIconStream`?

**Comment by Sculas** [comment]
Not the entire function, just the part for `readAllBytes`. So if we need to `readAllBytes`, we can reuse that code.

**Comment by ponces** [comment]
> Not the entire function, just the part for `readAllBytes`. So if we need to `readAllBytes` anywhere else, we can reuse that code.

Ah, understood! Great idea! Will do!

**Pull request merged**
