### PR TITLE
refactor(YouTube Music): Rename `Hide music video ads` to `Hide multimedia ads` and add patch description

### LINKED ISSUE #3378: bug(YouTube Music - Hide music video ads): Rename patch name and add description
### Bug description

Currently, Hide music video ads is a not an appropriate name as it not only hides music video ads, but song and podcast ads within YT Music as well.

### Error logs

_No response_

### Solution

Rename the patch to `Hide media ads` and the patch description to "Allows listening to music, podcasts and videos without ads." or "Hides ads played when listening to music, podcasts and videos."

### Additional context

_No response_

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by ILoveOpenSourceApplications**
Closes #3378

### CODE REVIEW

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]
Why is the `Hide music video ads` patch still present. Please check your changes before you push them.

**Comment by ILoveOpenSourceApplications** [comment]
> Why is the `Hide music video ads` patch still present. 

Where is it still present?

> Please check your changes before you push them.

I couldn't find anywhere else that required the changes. Sorry if I missed any.

**Comment by oSumAtrIX** [comment]
It's right next to the new added file: 

Screenshot_20240731-205644

**Comment by ILoveOpenSourceApplications** [comment]
I renamed the original file name to match the changes. So I'm confused how there's two files now.

**Comment by ILoveOpenSourceApplications** [comment]
I'm not seeing these duplicate files in my local system or in Android studio but only in my fork of the repo. So, how am I supposed to remove these files?

**Pull request closed without merging**
