### PR TITLE
fix(Spotify - Custom theme): Add more background surfaces coloring options

### PR DESCRIPTION
**Pull request by 4dvyte**
This change replaces background theme in many more places. Examples given in screenshots.

### CODE REVIEW

**Review by oSumAtrIX — COMMENTED** [review]
Do all backgrounds added here have the exact same color? If not, applying this patch would break color semantics of the app.

Please add a before and after screenshot of each surface color

**Comment by 4dvyte** [comment]
> Do all backgrounds added here have the exact same color? If not, applying this patch would break color semantics of the app.
> 
> Please add a before and after screenshot of each surface color

Yes all backgrounds have the exact same color.
here are the screenshots you asked for.

**Comment by 4dvyte** [comment]
> `grey_7` and `grey_15` are likely different shades of the same grey color.
> 
> Perhaps adjust the replacement color to match the same saturation as the original color, similar to how the YouTube custom seekbar color is applied to the different seekbar color variations used for different situations: https://github.com/ReVanced/revanced-integrations/blob/85705141a8b2eafd6095c3d98ac91708365f1e03/app/src/main/java/app/revanced/integrations/patches/theme/SeekbarColorPatch.java#L103-L124

Are you talking about player matching the album cover? that's not been touched. this change is made with respect to the latest spotify version "8.8.88.397"

**Comment by 4dvyte** [comment]
> > Are you talking about player matching the album cover? that's not been touched. this change is made with respect to the latest spotify version "8.8.88.397"
> 
> I don't use Spotify and I'm only speculating based on the color names.
> 
> If the replaced colors are all the same then there's no reason to adjust the replacement color.

Yes they are different shades. The point of this change is to unify the colors and apply the same color on all backgrounds. The player background still matches the Music/Album cover since it has not been changed.

**Comment by 4dvyte** [comment]
https://github.com/ReVanced/revanced-patches/pull/3285#issuecomment-1816678469

forgot to mention, the "before" screenshots are from the current revanced patch with background set to default ("@android:color/black")

**Comment by 4dvyte** [comment]
@LisoUseInAIKyrios I have removed gray_15 and decided not to unify that background color into one.

**Comment by 4dvyte** [comment]
I have made gray_15 as a second option instead.

**Comment by 4dvyte** [comment]
This PR is ready to be merged.

**Comment by oSumAtrIX** [comment]
Please allow pushing to the branch, otherwise I can not commit changes

**Comment by 4dvyte** [comment]
> Please allow pushing to the branch, otherwise I can not commit changes

Done

**Comment by 4dvyte** [comment]
All conflicts have been fixed. @oSumAtrIX

**Review by oSumAtrIX — APPROVED** [review]

**Pull request merged**
