### PR TITLE
feat(youtube/general-ads-patch): subscribers community guidelines rem…

### PR DESCRIPTION
**Pull request by 0xrxL**
…oval

https://github.com/revanced/revanced-integrations/pull/249

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Please explain this PR.

**Comment by 0xrxL** [comment]
> Please explain this PR.

I have a little problem explaining this PR, because at the moment I couldn't find a video that contained the component to be patched. I'll try to explain it anyway:

On some videos from channels that accept paid subscriptions, it is possible to filter the comments (with the chipbar) according to the users who have donated the most. In this new comments section there is a similar box, with specific rules for subscribed users:

Immagine 2022-12-23 224348

**Comment by 0xrxL** [comment]
To sum up: this patch just remove the guidelines box for the subscribers.

**Comment by 0xrxL** [comment]
Ok...I found an example on this video:

https://youtu.be/0Pymv3ExeP0

Screenshot_20221223_230149

**Review by oSumAtrIX — APPROVED** [review]

**Pull request merged**
