### PR TITLE
fix: `general ads` cleanup

### LINKED ISSUE #108: Further ad patches cleanup
Reel reference can be removed from this patch: https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/youtube/ad/general/bytecode/patch/GeneralBytecodeAdsPatch.kt

because has been moved to litho.

### LINKED ISSUE #167: problem: `old ads patches`
## 🐞 Issue

From the moment that Google moved (and still moving) so many stuff to litho, seems that old ads patches with id "ad_attribution" are not useful anymore.

## ⚙ Reproduce

Excluding them from patcher shouldn't change anything.

## 🛠 Solution

Deprecate patches.

### PR DESCRIPTION
**Pull request by OxrxL**
Closes #108
Closes  #167

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Does this apply to all supported versions of this patch? If not, remove them too.

**Comment by OxrxL** [comment]
> Does this apply to all supported versions of this patch? If not, remove them too.

There are just these as general ads reference inside "general ads patch".

There are no other things to remove (or at least I didn't find them).

**Comment by oSumAtrIX** [comment]
I am referring to the compatible versions this patch supports. Removing this code, does it guarantee it still works for said versions.

**Comment by OxrxL** [comment]
> I am referring to the compatible versions this patch supports. Removing this code, does it guarantee it still works for said versions.

Practically all, starting from 17.03.38 (which has begun to show ads on old Vanced version).

Google litho changes (partially, but almost noticeable) spread among many already released versions.

So, the last thing to do is push this PR and get feedbacks from users. And also roll back the XML ads patch (what is needed).

**Comment by oSumAtrIX** [comment]
Which xml ads patch do you mean? And rollback to what?

**Comment by OxrxL** [comment]
> Which xml ads patch do you mean? And rollback to what?

The ads resources patch which I requested to remove, due to supposed uselessness.

Restoring it will fix the ads on the tablet.

**Comment by oSumAtrIX** [comment]
Please open an issue for this

**Comment by OxrxL** [comment]
> Please open an issue for this

Done

**Comment by Sculas** [comment]
Status?

**Comment by OxrxL** [comment]
> Status?

Completed on my side. But seems @oSumAtrIX wants to finalize the settings before merge this (or maybe he would refactor the entire class, I don't know).

**Pull request closed without merging**
