### PR TITLE
Rebase feat/split

### PR DESCRIPTION
**Pull request by JavierFlores09**
This PR is just to rebase feat/split branch, because it was way behind main

### CODE REVIEW

**Comment by Sculas** [comment]
Don't think this is necessary, since my (upcoming) PR for the split branch already did this.

**Comment by oSumAtrIX** [comment]
> Don't think this is necessary, since my (upcoming) PR for the split branch already did this.

To avoid situations like this, it is adviced to create an issue to track that it is already being worked on so that a faster PR than yours does not obstruct yours.

**Comment by JavierFlores09** [comment]
> Don't think this is necessary, since my (upcoming) PR for the split branch already did this.

I just did this because I also planned to work on the branch, and if I just rebased and did my changes on top, then PR'd, we'd be again at merge-conflict hell when it came to your PR or any other change from team (as rebasing itself caused conflicts).

As osum said, a heads up with an issue or in #development would've been nice, either way if you believe you are indeed going to PR your changes then I can just close this

**Comment by Sculas** [comment]
I stopped working on my PR due to certain issues, so this PR can be merged if wanted.

**Comment by oSumAtrIX** [comment]
I am not sure how merging this PR will behave, will it actually rebase or add all those commits on top?

**Comment by JavierFlores09** [comment]
> I am not sure how merging this PR will behave, will it actually rebase or add all those commits on top?

I believe the latter since the rebased commits are are newer, if you want them to appear as they're newer I can do that though

**Comment by oSumAtrIX** [comment]
Rebasing is not possible, to rebase it is required to force push to this branch which is why this PR should be closed for now.

**Pull request closed without merging**
