### PR TITLE
feat: bump patches compatibility to v17.38.36

### PR DESCRIPTION
**Pull request by divyam234**

### CODE REVIEW

**Comment by divyam234** [comment]
all patches are working fine during testing

**Comment by oSumAtrIX** [comment]
Tested?

**Comment by NR8124** [comment]
image
seems every patches is succeed.

**Comment by oSumAtrIX** [comment]
Did you test the patches?

**Comment by nkoc6a15** [comment]
Confirm. YouTube version: 17.39.34 working fine too

**Review by nkoc6a15 — APPROVED** [review]

**Review by E85Addict — APPROVED** [review]

**Review by GeekCornerGH — APPROVED** [review]

**Review by NR8124 — APPROVED** [review]

**Comment by Issam28** [comment]
I tested V17.38.36 with the newer patches/ integration releases and it crashed instantly.

**Pull request closed without merging**
