### PR TITLE
feat(id-austria): remove version constraint

### PR DESCRIPTION
**Pull request by 1fexd**
Just tested the patch for version `2.6.1`, and it still works.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Probably dropping the version constraint is a good idea.

**Comment by 1fexd** [comment]
But what if they change something which breaks the patch in the future?

**Comment by oSumAtrIX** [comment]
That is obviously a risk, but it always depends on the patch's resilience. I believe in this case it should be fairly resilient considering the implementation.

**Comment by 1fexd** [comment]
Alright, I have removed the versions array

**Review by oSumAtrIX — APPROVED** [review]

**Pull request merged**
