### PR TITLE
feat: [Tiktok patch] Add tiktok-download and tiktok-seekbar patch.

### PR DESCRIPTION
**Pull request by d4rkk3y**
`tiktok-download` bypass downloads restriction on all video and remove watermark on downloaded videos.
`tiktok-seekbar` enable progresss bar for all video.

### CODE REVIEW

**Comment by d4rkk3y** [comment]
Relevant discussion #509

**Comment by E85Addict** [comment]
I'm testing the patches and the download patch works flawless, the seekbar patch is being hit or miss, I see it on some videos but not all and I'm not sure if its meant to be select-able to scrobble but that only worked on longer videos, I'd love to help debug however I can just let me know.

**Comment by d4rkk3y** [comment]
> Edit: After some further testing it works great, both patches. My only question is with the seekbar patch is it possible to also make it scrobble like youtubes seekbar tapping as well, TikTok already allows this for its longer videos so maybe it can be made to work for all of them, it's also a common feature amongst other closed source tik tok mods.

Did you mean tapping to seek to a timestamp of video? When I test I can seek to a point on any video by hold and swipe.

**Comment by E85Addict** [comment]
> > Edit: After some further testing it works great, both patches. My only question is with the seekbar patch is it possible to also make it scrobble like youtubes seekbar tapping as well, TikTok already allows this for its longer videos so maybe it can be made to work for all of them, it's also a common feature amongst other closed source tik tok mods.
> 
> Did you mean tapping to seek to a timestamp of video? When I test I can seek to a point on any video by hold and swipe.

Yes exactly that, I am only able to do that to long TikToks, is it possible to allow that to all of them?

**Comment by E85Addict** [comment]
So from what I've gathered any less than 15-30 seconds do not have the ability to tap and hold a timestamp but any of that length and longer they do

**Comment by d4rkk3y** [comment]
> So from what I've gathered any less than 15-30 seconds do not have the ability to tap and hold a timestamp but any of that length and longer they do

I can not reproduce the issue. For me all video can be seek by hold and swipe.
https://drive.google.com/file/d/1Li2szZyOJ91ivgdT1Ek6suCiRXSPG2YQ/view?usp=sharing

**Comment by E85Addict** [comment]
> > So from what I've gathered any less than 15-30 seconds do not have the ability to tap and hold a timestamp but any of that length and longer they do
> 
> I can not reproduce the issue. For me all video can be seek by hold and swipe. Please let's me know the package name and version that you used to get the issue. https://drive.google.com/file/d/1Li2szZyOJ91ivgdT1Ek6suCiRXSPG2YQ/view?usp=sharing

https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/tik-tok-25-9-4-release/tiktok-25-9-4-3-android-apk-download/ 

This is the exact version, I will rebuild it to see if it persists

**Comment by d4rkk3y** [comment]
> This is the exact version, I will rebuild it to see if it persists

I can reproduce the issue in that version. I will try to fix that.

**Comment by d4rkk3y** [comment]
@E85Addict  fixed in the c4748877e947614991447e27306045784d28ce94.

**Comment by E85Addict** [comment]
> @E85Addict fixed in the [c474887](https://github.com/revanced/revanced-patches/commit/c4748877e947614991447e27306045784d28ce94).

You're amazing, I will test as well.

**Comment by TheJeterLP** [comment]
Now this needs to get merged :)

**Review by Sculas — APPROVED** [review]

**Review by Sculas — APPROVED** [review]

**Pull request merged**
