### PR TITLE
Lock File Maintenance

### PR DESCRIPTION
**Pull request by CanerKaraca23**

### CODE REVIEW

**Review by oSumAtrIX — COMMENTED** [review]
Shouldn't this be handled by dependabot?

**Comment by CanerKaraca23** [comment]
> Shouldn't this be handled by dependabot?

Unfortunately no, dependabot can't detect and handle all of lock file contents, but after this PR, it will handle some (maybe all) dependencies on lock file on every dependency pull requests.

**Comment by oSumAtrIX** [comment]
What is the change that makes Dependabot handle the lock file after this PR?

**Comment by CanerKaraca23** [comment]
> What is the change that makes Dependabot handle the lock file after this PR?

For example in this dependabot PR https://github.com/ReVanced/revanced-patches/pull/2573/files , it updates only "gradle-semantic-release-plugin" related dependencies on lock file, not every lock file contents. This PR makes lock file up-to-date so dependabot will try continue to keep it "up-to-date".

**Comment by oSumAtrIX** [comment]
I am reluctant to merge such PRs as they can infiltrate handcrafted malicious dependencies this way. Is there a transparent/CI solution? Otherwise, I'll bump them on my end for this PR.

**Comment by CanerKaraca23** [comment]
> I am reluctant to merge such PRs as they can infiltrate handcrafted malicious dependencies this way. Is there a transparent/CI solution? Otherwise, I'll bump them on my end for this PR.

This lock file automatically generated by Renovate bot (it's well-known dependabot alternative). I don't know any CI solution. I used renovate bot to generate this file but i don't prefer renovate for automatic dependency updates because dependabot is better than renovate by detecting/updating dependencies. However, you can add renovate to your repository too for only lock file maintenance and disable dependency updates, but eeh, manually updating is preferable i think.

**Comment by oSumAtrIX** [comment]
Superseded by 66da935519b2e0b72105d766634e06ca1a706d34. thanks for reminding to update.

**Comment by CanerKaraca23** [comment]
> Superseded by [66da935](https://github.com/ReVanced/revanced-patches/commit/66da935519b2e0b72105d766634e06ca1a706d34). thanks for reminding to update.

You're welcome.

**Comment by CanerKaraca23** [comment]
> Superseded by [66da935](https://github.com/ReVanced/revanced-patches/commit/66da935519b2e0b72105d766634e06ca1a706d34). thanks for reminding to update.

@oSumAtrIX Are you sure you properly updated the lock file? Looks like you downgraded @saithodev/semantic-release-backmerge from 4.0.1 to 3.2.1 and renovate bot change it back with huge difference (Actually reverts your changes back). You can check the commit on my fork, i can PR if you want, build passes successfully:

https://github.com/CanerKaraca23/revanced-patches/pull/4/commits/3ce03140a6b2615e51d7056e0607165c92594759

**Comment by oSumAtrIX** [comment]
I've used `npm update`

**Pull request closed without merging**
