### PR TITLE
fix(sponsorblock): fix wording of "privateID"

### PR DESCRIPTION
**Pull request by mchangrh**
The current wording of the "privateID/ userID" is causing revanced users to constantly leak their privateIDs in the SponsorBlock discord.

The point of this wording to change is to explicitly reinforce that this is not the public component, this is the private component.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
I remember SponsorBlock referring to it as public id somewhere. Is it really private?

**Comment by Canny1913** [comment]
> I remember SponsorBlock referring to it as public id somewhere. Is it really private?

I don't remember that being referred anywhere.

**Comment by oSumAtrIX** [comment]
image

German for "Public".

**Comment by mchangrh** [comment]
> I remember SponsorBlock referring to it as public id somewhere. Is it really private?

The "UUID" that the string describes is the privateID components

image

the public component is not displayed in reVanced except in the username

**Comment by mchangrh** [comment]
the publicID is derived from the publicID, if you copy your "UserID" from the extension options and paste it in that field, you'll get the same "username" which defaults to publicID unless explicitly set - if you instead copy your "username" you'll get a completely different "username"

**Comment by oSumAtrIX** [comment]
I think it makes more sense to keep this the user id, the same as SponsorBlock refers to, but add the same notice to the UI.

**Comment by mchangrh** [comment]
> I think it makes more sense to keep this the user id, the same as SponsorBlock refers to, but add the same notice to the UI.

The issue is that people are mistaking it for the public component, which can be shared freely. People are not reading past the title and I don't think an additional toast will suffice

**Comment by oSumAtrIX** [comment]
A toast would not suffice it would need to be a notice just like SponsorBlock's.

**Comment by mchangrh** [comment]
https://github.com/ajayyy/SponsorBlock/pull/1490 merged upstream in browser extension

**Comment by oSumAtrIX** [comment]
it still refers to the id as private `userId`, not `privateId`.

**Pull request merged**
