### PR TITLE
fix: `default-video-quality` patch crashing

### PR DESCRIPTION
**Pull request by Canny1913**
Tested on 17.28.34.

Requires:
- https://github.com/revanced/revanced-integrations/pull/100

### CODE REVIEW

**Comment by TheJeterLP** [comment]
please use fix just for version bumps in the future :)

**Comment by Canny1913** [comment]
The patch causes new YT versions to crash.
Needs to be fixed

**Comment by Canny1913** [comment]
These can be merged as well.

**Comment by TheJeterLP** [comment]
Both PRs look good to me. I want to wait what Osu says

**Review by oSumAtrIX — COMMENTED** [review]
The SMALI code is unformatted, looks good other than that. I added a comment to the other PR as well.

**Comment by TheJeterLP** [comment]
> The SMALI code is unformatted, looks good other than that. I added a comment to the other PR as well.

I dont see any unformatted smali code?

**Comment by oSumAtrIX** [comment]
Thanks!

**Pull request merged**
