### PR TITLE
fix: change download icon to match other icons

### PR DESCRIPTION
**Pull request by afnzmn**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Whats the difference to #434?

**Comment by afnzmn** [comment]
> Whats the difference to #434?

The PR isn't opened by Ushie.
Also, I remade the icon so its slightly different from that of YouTube's.

**Comment by oSumAtrIX** [comment]
Why should this PR be merged instead of #464?

**Comment by afnzmn** [comment]
In #434 you question whether the icon Ushie took from YouTube complies with GPLv3 license.

**Pull request merged**
