### PR TITLE
feat: `materialyou` patch 

### PR DESCRIPTION
**Pull request by datnerdguy**
For now exclude amoled patch while patching (I don't know how to exclude a patch when another is selected so if someone could help me out I would be very much thankful)

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
This patch should be combined with the amoled patch to a themer patch. Otherwise they conflict each other

**Comment by datnerdguy** [comment]
How should I visualise the selection ui then?

**Comment by oSumAtrIX** [comment]
YouTube has a setting to switch between light and dark mode, this would fit there.

**Comment by datnerdguy** [comment]
Will reopen this pr wen I am ready.

**Pull request closed without merging**
