### PR TITLE
fix(YouTube/shorts button remover): improved fingerprint

### PR DESCRIPTION
**Pull request by OxrxL**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Why is this required?

**Comment by Canny1913** [comment]
> Why is this required?

Fingerprint fails on latest versions.

**Comment by OxrxL** [comment]
> > Why is this required?
> 
> Fingerprint fails on latest versions.

Exactly.

**Comment by oSumAtrIX** [comment]
The latest versions are not supported. If you intend to, please do so in a single PR.

**Pull request closed without merging**
