### PR TITLE
feat: revert `block-embedded-ads` patch

### PR DESCRIPTION
**Pull request by Ushie**
RE: https://github.com/revanced/revanced-patcher/issues/126

Depends on:

- https://github.com/revanced/revanced-integrations/pull/230

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Reason?

**Comment by Canny1913** [comment]
Patch is crashing the app due to issue:
- https://github.com/revanced/revanced-patcher/issues/126

**Comment by oSumAtrIX** [comment]
Please open a draft PR afterwards to add the patch back with the dependency to https://github.com/revanced/revanced-patcher/issues/126.

**Comment by Ushie** [comment]
Will do

**Pull request merged**
