### PR TITLE
fix: listing of wrong fingerprint class

### PR DESCRIPTION
**Pull request by ponces**

### CODE REVIEW

**Comment by TheJeterLP** [comment]
That is not the wrong fingerprint?

**Comment by TheJeterLP** [comment]
Thanks for that

**Comment by ponces** [comment]
I still need to fix this patch but at least is not throwing an exception when applying

**Comment by ponces** [comment]
> I still need to fix this patch but at least is not throwing an exception when applying

Actually, this patch (apparently) doesn't make sense as it is patching the return statement by replacing void by a value in a function which states void to be the return type. Right? I'm still not to familar with this type of development work but I guess I am interpreting this right...

@oSumAtrIX you were the one to push the original code. Was this based on some previous patches from Vanced team?

**Comment by ponces** [comment]
> > I still need to fix this patch but at least is not throwing an exception when applying
> 
> Actually, this patch (apparently) doesn't make sense as it is patching the return statement by replacing void by a value in a function which states void to be the return type. Right? I'm still not too familar with this type of development work but I guess I am interpreting this right...
> 
> @oSumAtrIX you were the one that pushed the original code on b60c9d33b611bb4d5b55bb419652bc14b0309792.
> Was this based on some previous patches from Vanced team?
> 

Patch is being applied on wrong method. I'll push a new PR with the working (already tested) fix for this patch

**Comment by ponces** [comment]
> Which patch is not working?

Sorry, i was not clear.

I meant exclusive audio patch

**Pull request merged**
