### PR TITLE
fix: alignment of copy icon

### PR DESCRIPTION
**Pull request by kazimmt**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
What does this PR do?

**Comment by kazimmt** [comment]
> What does this PR do?

Match the size of Copy URL icon & Copy Url with timestamp icon with Download & Full screen icon
& it follow Material Symbol icon which is also used for download icon

Here is the before 
Screenshot_2023-01-02-15-47-18-840_app rv android youtube-edit

& here is after
Screenshot_2023-01-02-16-12-30-421_app rv android youtube-edit

**Comment by oSumAtrIX** [comment]
What happened to the other PR?

**Comment by kazimmt** [comment]
> What happened to the other PR?

The only thing happen on the last PR is my lack of knowledge (I'm still new with GitHub stuffs & learning)

**Comment by kazimmt** [comment]
after last commit, the `copy url` icon will look like this
210236406-2114f56d-4622-4189-8745-7bc2ce9ddaa6

**Comment by oSumAtrIX** [comment]
Please rebase onto the `dev` branch, otherwise we cant squash.

**Pull request merged**
