### PR TITLE
fix: pixelated icon issue

### PR DESCRIPTION
**Pull request by kazimmt**

### CODE REVIEW

**Comment by kazimmt** [comment]
Screenshot_2022-11-11-14-38-17-414_com miui home-edit
Screenshot_2022-11-11-14-43-55-653_com miui home-edit

Here is the comparison

**Comment by trmdi** [comment]
Should this be applied to Revanced Manager too? I feel there is a small difference here.
IMG_20221112_125113

Or does Revanced Manager need a different icon?

**Comment by oSumAtrIX** [comment]
Yeah, this should be applied to the ReVanced Manager too. If possible open an issue or PR regarding this.

**Comment by kazimmt** [comment]
> Yeah, this should be applied to the ReVanced Manager too. If possible open an issue or PR regarding this.

Ok, i'll

**Pull request merged**
