### PR TITLE
fix: actually use original app name

### PR DESCRIPTION
**Pull request by PalmDevs**
Makes the `music-microg-support` use the original app name instead of appending ReVanced. MicroG support patch shouldn't be changing the app name in the first place.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
The MicroG patch changes the package name, respectively the name of the app should be changed as well, otherwise the app name will conflict with the original packages app name. For that reason the respective patch for branding has to be abstracted. The abstraction should allow for patches to extend on it. These patches can then be depended on, such as by the MicroG patch.

**Comment by Ehab-d** [comment]
@oSumAtrIX If you are right, why would a YouTube app build with the original display name if a custom-branding patch is included? Please add custom-branding patch for YT Music. The current display name of the app is taking two lines on my launcher. This looks so bad,

**Comment by oSumAtrIX** [comment]
@Ehab-d The custom branding patch only changes the icon iirc, not the package name.

**Comment by Ushie** [comment]
It changes the Icon and App name

**Comment by oSumAtrIX** [comment]
Right, that is the case for YouTube, but not YouTube Music.

**Pull request closed without merging**
