### PR TITLE
fix: bump youtube version to 17.29.34

### PR DESCRIPTION
**Pull request by Canny1913**
(yes i wrote the commit name wrong again)

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Has this been tested before getting merged?

**Comment by TheJeterLP** [comment]
> Has this been tested before getting merged?

canny tested them

**Comment by Canny1913** [comment]
Only microg fingerprints needed to be modified, other patches work fine.

**Comment by oSumAtrIX** [comment]
Looks good, it was unnecessarily huge.

**Pull request merged**
