### PR TITLE
feat(ytmusic): remove compatibility constraint on all patches

### PR DESCRIPTION
**Pull request by EvadeMaster**
✨ Feature - YouTube Music - remove compatibility constraint on all patches
> Originally was: Bump compatibility from v5.41.50 to v5.44.53

## Testing Environment

💻 PC (64-bits) - `ReVanced CLI` v2.20.0 - No ReVanced Integration - Install without mounting
> Status: ✅ Working `5.41.51` - `5.44.53`

## Tested versions
These versions have been tested against a real device.

- [x] 5.41.51 - ✅ Working - Recommended settings with MicroG Support
- [x] 5.42.50 - ✅ Working - Recommended settings with MicroG Support
- [x] 5.42.51 - ✅ Working - Recommended settings with MicroG Support
- [x] 5.43.55 - ✅ Working - Recommended settings with MicroG Support
- [x] 5.43.56 - ✅ Working - Recommended settings with MicroG Support
- [x] 5.44.52 - ✅ Working - Recommended settings with MicroG Support
- [x] 5.44.53 - ✅ Working - Recommended settings with MicroG Support

> **Note**: `hide-get-premium` might have a chance to appear on your device, but during testing, these have never appeared (see comments on #1551 & #1541)

## Logs
Nothing here... since they all produced the same result if you insist.

```
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Skipping compact-header: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
INFO: background-play succeeded
INFO: codecs-unlock succeeded
INFO: exclusive-audio-playback succeeded
INFO: hide-get-premium succeeded
INFO: minimized-playback-music succeeded
INFO: music-microg-support succeeded
INFO: music-video-ads succeeded
INFO: tasteBuilder-remover succeeded
INFO: upgrade-button-remover succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Aligning com.google.android.apps.youtube.music_{version}_minAPI21(arm64-v8a)(nodpi)_apkmirror.com.apk to patched-output_aligned.apk
INFO: Signing patched-output_aligned.apk to patched-output_signed.apk
INFO: Found existing keystore: patched-output.keystore
INFO: Copying patched-output_signed.apk to patched-output.apk
INFO: Installing without mounting
INFO: Finished
```

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Seems like the compatibility list grows quite a lot. That indicates that the constraint on the app version for these patches can be removed entierly.

**Comment by NeeRaj-2401** [comment]
> That indicates that the constraint on the app version for these patches can be removed entierly.


image

**Comment by oSumAtrIX** [comment]
I don't know what this screenshot means. Please do as suggested.

**Comment by oSumAtrIX** [comment]
Thanks! As always superb PR!

**Pull request merged**
