### PR TITLE
Enable reels(stories) shelf

### PR DESCRIPTION
**Pull request by johnconner122**

### CODE REVIEW

**Comment by OxrxL** [comment]
Make referring to this for ads: https://github.com/revanced/revanced-patches/pull/641

**Comment by oSumAtrIX** [comment]
Please explain this PR and why it is required.

**Comment by johnconner122** [comment]
it enables the stories shelf (like shorts) on homepage

**Comment by oSumAtrIX** [comment]
The code committed calls a method to hide reels though, so how does it enable stories shelf?

**Pull request closed without merging**
