### PR TITLE
fix(tiktok/settings): tiktok's settings patch name make 'revanced manager' confuse with youtube settings patch name

### PR DESCRIPTION
**Pull request by d4rkk3y**
https://discord.com/channels/952946952348270622/1044056142864711751

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
This shouldn't happen. Patches are constrained to their respective package. Meaning, if you have selected TikTok, it should show patches for TikTok. That way you wouldn't he able to include a patch from YouTube.

**Comment by oSumAtrIX** [comment]
This could be a problem with the ReVanced Manager including the wrong patch.

**Comment by d4rkk3y** [comment]
Yes, this is a problem with Revanced Manager because it is fine when patching with RevancedCLI. This PR is just a temporary fix for Revanced Manager. If it is better to wait for Revanced Manager to fix this issue, then please close this PR.

**Comment by oSumAtrIX** [comment]
Can you open a draft PR to remove "tiktok" from the tiktok patches after this PR is merged. That way we can merge it after it is fixed on the ReVanced Manager side.

**Pull request merged**
