### PR TITLE
fix(youtube/custom-branding): use highest resolution adaptive icons

### PR DESCRIPTION
**Pull request by LisoUseInAIKyrios**
I fixed the tiny app icon, and also increased the size of the adaptive images to the full resolution (108px, 162px, 216px, 324px, 432px)

I did this using the original high resolution image here on [GitHub](https://avatars.githubusercontent.com/u/101597779?s=2000&v=4).  By coincidence, it was the ideal size.

I also updated the old legacy ic_launcher.png and ic_launcher_round.png, although I don't think those are ever used because Android 8 uses the adaptive icons (and YouTube requires Android 8 or higher).

Before:
before

After:
after (whose the tiny one now?)

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
It seems like the size is a bit off, here are the resources for the ReVanced logo with source and SVG files as reference: [revanced-brand-identity.zip](https://github.com/revanced/revanced-patches/files/10551694/revanced-brand-identity.zip).

**Comment by oSumAtrIX** [comment]
While it might look personally better, we should remain consistent with branding. In favour of brand consistency, it is required for the logo to match the exact size of the original logo.

**Comment by oSumAtrIX** [comment]
I believe the right one is the patched YouTube app. If so, this PR is ready for merge

**Comment by oSumAtrIX** [comment]
That sounds reasonable to me. Currently there is also the repo for the compose ReVanced Manager app, which might be relevant as well.

**Comment by oSumAtrIX** [comment]
Thanks!

**Comment by kazimmt** [comment]
@oSumAtrIX the edge of the changed is not correct :) 
adaptiveproduct_youtube_foreground_color_108

**Comment by oSumAtrIX** [comment]
Yep, I noticed already, will have to be fixed before merge to main

**Comment by oSumAtrIX** [comment]
Iirc thats an Android specification.

**Comment by kazimmt** [comment]
> The image is stacked together with the background PNG, so it should never be seen individually. I will recreate using a variable alpha layer.
> 
> Is there a reason for both a foreground and background image? Why not use just 1 image?

I think everything was fine on last version
Except adaptiveproduct_youtube_foreground_color_108 in mipmap-xxxhdpi folder

Mistakenly it was a little small compare to others

**Comment by kazimmt** [comment]
> I recreated them all using `revanced-logo-shape.svg`
> 
> new PR: #1576

Ok, whatever
It needs fix again
I'll wait till logo poll

**Comment by oSumAtrIX** [comment]
The ReVanced Manager app is also using wrong icon sizes, you should not match against it

**Comment by kazimmt** [comment]
> The ReVanced Manager app is also using wrong icon sizes, you should not match against it

The main icon (from branding zip) is not correctly aligned tho. (my 600% zoom -_- )

**Comment by oSumAtrIX** [comment]
@kazimmt it is aligned, you can check the source file or inspect the svg path to confirm.

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios Why is a scaling required at all? Can't the svg directly be used as the logo?

**Comment by kazimmt** [comment]
> @kazimmt it is aligned, you can check the source file or inspect the svg path to confirm.

Check Discord. I've already post the ss about alignment error.

**Comment by oSumAtrIX** [comment]
I don't know what you refer to.

**Comment by Ushie** [comment]
> > @kazimmt it is aligned, you can check the source file or inspect the svg path to confirm.
> 
> Check Discord. I've already post the ss about alignment error.

It is not possible to keep track of messages related to this issue in the Discord, please provide a screenshot of it here aswell

**Comment by oSumAtrIX** [comment]
Isn't it intended to use a logo without any padding at all? If the icon has a padding, shouldn't it be removed entirely for that reason instead of just cutting it doen by 5%??

**Comment by oSumAtrIX** [comment]
I was refering to the padding of the background circle. Lets say that padding is 10px. Then you'd remove the same amount of padding for the shape as well.

**Comment by oSumAtrIX** [comment]
That's interesting. Android seems to apply a negative padding (zooming into the logo). Is the padding value documented?

**Comment by kazimmt** [comment]
> That's interesting. Android seems to apply a negative padding (zooming into the logo). Is the padding value documented?

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

ic_launcher_foreground

adaptive-icon-foreground-background

**Comment by oSumAtrIX** [comment]
@LisoUseInAIKyrios I see the motivation behind using an 1/6th padding ratio, though if we would use that, the full logo would look off. The original padding of the shape in the logo project file was used in the shape svg file in order to correctly match in size with the full logo svg. Do you have any suggestions regarding this?

**Comment by kazimmt** [comment]
@LisoUseInAIKyrios why not we include the gradient background also?
It's part of logo background. Right?

**Comment by oSumAtrIX** [comment]
I believe what he means is something like on the README file:

Logo

**Comment by kazimmt** [comment]
> I believe what he means is something like on the README file:
> 
> Logo

Exactly

**Comment by kazimmt** [comment]
I'm worried about this shape
216123197-c8d03e32-19c2-40cf-b14e-b68303b88986
Who use these 😅

**Comment by kazimmt** [comment]
> I believe what he means is something like on the README file:
> 
> Logo

Btw README.md logo also needs fix (as per branding guide)

**Comment by oSumAtrIX** [comment]
Please PR or open an issue regarding this. @kazimmt

**Comment by oSumAtrIX** [comment]
> t'll look almost the same

I think whats necessary is a certain padding: 



It should be noted that the correct padding would have to be added for Android in order to allow for the gradient border to look like this:

Logo

**Comment by kazimmt** [comment]
@oSumAtrIX i think icon pack also matters
I test on miui with different icon pack
& here is the result

Screenshot_2023-02-02-00-33-20-619_com miui packageinstaller-edit
Screenshot_2023-02-02-00-34-01-760_com miui home-edit
Screenshot_2023-02-02-00-37-37-712_com miui home-edit
Screenshot_2023-02-02-00-38-37-773_com miui home-edit
Screenshot_2023-02-02-00-39-46-035_com miui home-edit

**Comment by oSumAtrIX** [comment]
In that case, the gradient should not be added.

**Comment by kazimmt** [comment]
> In that case, the gradient should not be added.

Maybe there is another way
Let me try it

**Comment by kazimmt** [comment]
> And the results:
> 
> squaresquirclecircleteardrop

Looks Good

**Comment by kazimmt** [comment]
> > Maybe there is another way Let me try it
> 
> What exactly was in that icon test pack?

It's ReVanced Manager -_- 
I just changed the name & package for testing -_-

**Comment by kazimmt** [comment]
Needs test on Memeui (MIUI) & Other OS too

**Comment by oSumAtrIX** [comment]
Time to move to https://github.com/revanced/revanced-manager/pull/675. Thanks!

**Pull request merged**
