### PR TITLE
feat(Digitales Amt): Bump compatibility to `3.0.2`

### PR DESCRIPTION
**Pull request by 1fexd**
Adds support for ID Austria/Digitales Amt version `3.0.2`

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Please resolve the merge conflicts.

**Comment by notimp** [comment]
> Done

Build seemed to have failed? (Maybe its some part thats not important? I'm not familiar 
 with the project.)

**Comment by oSumAtrIX** [comment]
I have pushed some refactoring changes, please check if it looks good to you.

**Comment by 1fexd** [comment]
I checked your refactoring and added a small tweak to allow the return value to be explicitly specified by the patch developer for the util method you added @oSumAtrIX as my patch needs to return `0x1` (true) instead of false

**Pull request merged**
