### PR TITLE
feat(Facebook): Add `Hide story ads` patch

### PR DESCRIPTION
**Pull request by Loukious**

### CODE REVIEW

**Comment by Loukious** [comment]
@LisoUseInAIKyrios anything else I should change?

**Comment by cyberboh** [comment]
@Loukious which facebook version that compatible with this patch? 
tried v440.0.0.31.105 but patches can't be applied

**Comment by Loukious** [comment]
> @Loukious which facebook version that compatible with this patch? tried v440.0.0.31.105 but patches can't be applied

It's not version specific. It should work until they actually remove specific strings from the package. It's compiling just fine using that same version for me.

**Comment by cyberboh** [comment]
> > @Loukious which facebook version that compatible with this patch? tried v440.0.0.31.105 but patches can't be applied
> 
> It's not version specific. It should work until they actually remove specific strings from the package. It's compiling just fine using that same version for me.

I get this error while compiling:
```
SEVERE: Hide story ads failed:
app.revanced.patcher.patch.PatchException: Failed to resolve FetchMoreAdsFingerprint
        at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:24)
        at app.revanced.patches.facebook.ads.story.HideStoryAdsPatch.execute(HideStoryAdsPatch.kt:24)
        at app.revanced.patches.facebook.ads.story.HideStoryAdsPatch.execute(HideStoryAdsPatch.kt:12)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:237)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:236)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
```
Downloaded this apk 
`https://www.apkmirror.com/apk/facebook-2/facebook/facebook-440-0-0-31-105-release/facebook-440-0-0-31-105-9-android-apk-download/download/?key=a0684757e2b82ffaa3011eb85efa8df24f2af488&forcebaseapk=true`

**Comment by oSumAtrIX** [comment]
Try 441 and up

**Comment by cyberboh** [comment]
@oSumAtrIX @Loukious I know the culprit, patches only works with Facebook for Android 11+ 
Tried this apk and it works:
`https://www.apkmirror.com/apk/facebook-2/facebook/facebook-441-0-0-32-109-release/facebook-441-0-0-32-109-9-android-apk-download/download/?key=fd880d163c31f843a6c430cf6e58ce552d0b9dc0&forcebaseapk=true`

But failed with Facebook apk for Android 9+ like this:
`https://www.apkmirror.com/apk/facebook-2/facebook/facebook-440-0-0-31-105-release/facebook-440-0-0-31-105-9-android-apk-download/download/?key=a0684757e2b82ffaa3011eb85efa8df24f2af488&forcebaseapk=true`

My device running android 10, so i choose Android 9+ version. It imposible for me to choose apk for Android 11+, it will failed to installed in my device though.

**Comment by Loukious** [comment]
@cyberboh can confirm that it's the case. Only work on A11+ package.

**Comment by cyberboh** [comment]
> @cyberboh can confirm that it's the case. Only work on A11+ package.

Does possible to make patches compatible to Android 9 too?

**Pull request merged**
