### PR TITLE
Use original shortcut label for YT Music

### PR DESCRIPTION
**Pull request by AMSAMSAMSAMS**
Instead of **YT Music**, just use the original name YouTube Music.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
The original name is `YT Music`: https://github.com/revanced/revanced-patches/pull/977

**Comment by AMSAMSAMSAMS** [comment]
and drop the Revanced from the name to make it shorter....

**Comment by oSumAtrIX** [comment]
Then it is indistinguishable from the unpatched app.

**Comment by AMSAMSAMSAMS** [comment]
> Then it is indistinguishable from the unpatched app.

Same with unbranded YouTube, right?
if the user wish, they can exclude the branding manually via switch... (-e custom-branding -e theme -e amoled)..
The default one is the branded one...

**Comment by oSumAtrIX** [comment]
I am not sure what you mean.

**Comment by AMSAMSAMSAMS** [comment]
> I am not sure what you mean.

The YouTube (not music) app have switch to use it with branding (YouTube ReVanced) or not (YouTube only with original logo, indistingushable from original one), right?

Can you implement the same with YT Music?

Refer to this:
`@Patch
@Name("custom-branding")
@Description("Changes the YouTube launcher icon and name to your choice (defaults to ReVanced).")
@CustomBrandingCompatibility
@Version("0.0.1")
class CustomBrandingPatch : ResourcePatch {
    override fun execute(context: ResourceContext): PatchResult {
        fun copyResources(resourceGroups: List<ResourceUtils.ResourceGroup>) {
            iconPath?.let { iconPathString ->
                val iconPath = File(iconPathString)
                val resourceDirectory = context["res"]`

**Comment by oSumAtrIX** [comment]
A PR or issue already exists for that. Required refactoring iirc.

**Pull request closed without merging**
