### PR TITLE
feat: `quality-preference` patch

### PR DESCRIPTION
**Pull request by Canny1913**
Note: Signatures are working now thanks to @bogadana

### CODE REVIEW

**Comment by Sculas** [comment]
May I ask, why are you adding patches such as `video-buffer` to the same branch as the `quality-preference` patch?
It's not logical to merge this PR anymore due to this. Please make separate branches for PRs and redo them.

**Comment by oSumAtrIX** [comment]
Revert the commit and push to a new branch. No need to close.

**Comment by Sculas** [comment]
There are lots of commits to this branch. Some of them are unrelated. They'd have to revert all of those. That just doesn't make sense, it's better to just copy the changes and move them to a fresh new branch.

**Comment by Canny1913** [comment]
> May I ask, why are you adding patches such as `video-buffer` to the same branch as the `quality-preference` patch? It's not logical to merge this PR anymore due to this. Please make separate branches for PRs and redo them.

Yes it automatically added and i didn't know. My bad.

I'll open a new one when i fix the errors.

**Pull request closed without merging**
