### PR TITLE
feat: bump compatibility for patches for Youtube to v17.23.35

### PR DESCRIPTION
**Pull request by TheJeterLP**
Tested the patches on 17.23.35 and they all work fine, so this YouTube version should be added.

### CODE REVIEW

**Comment by TheJeterLP** [comment]
Need to add another commit, wait a sec

**Comment by oSumAtrIX** [comment]
Thanks!

**Comment by Lyceris-chan** [comment]
This [https://github.com/revanced/revanced-patches/pull/39/commits/44082bba888f9d7f90edbaa56686c968aa05030e](commit) says 12.23.35 instead of 17.23.35.

The rootless variant works fine on my Pixel 5 running A13 beta 3.2

**Comment by TheJeterLP** [comment]
> This [https://github.com/revanced/revanced-patches/pull/39/commits/44082bba888f9d7f90edbaa56686c968aa05030e](commit) says 12.23.35 instead of 17.23.35.
> 
> The rootless variant works fine on my Pixel 5 running A13 beta 3.2

I can't find anything that says 12 instead of 17?

**Pull request merged**
