### PR TITLE
feat(syncforreddit): add `change-oauth-client-id` patch

### PR DESCRIPTION
**Pull request by oSumAtrIX**
## About

This PR adds a patch for "Sync for Reddit" to change the client id to circumvent the upcoming restrictions on the API enforced by Reddit.

## TODO

- [x] Grabbing the token from the authorization fails with the toast "Error grabbing token", this should be fixed.

### CODE REVIEW

**Comment by quyleanh** [comment]
@oSumAtrIX sorry for taking your time but could you describe more detail about this patch?

As I understand, when Reddit changes their API, we can use our own credential and patch directly to this app, right?

I'm using the folked repo with Github Action build from j-hc, but [there is error](https://github.com/quyleanh/revanced-magisk-module/actions/runs/5268062896/jobs/9524199442#step:6:1236). Since I don't know how to add client ID, could you tell me how to patch it? I patched with revanced-integrations but it didn't work. Thank you.

```
SEVERE: change-oauth-client-id failed: 
app.revanced.patcher.patch.PatchResultError: No client ID provided
	at app.revanced.patches.syncforreddit.api.patch.ChangeOAuthClientIdPatch.execute(ChangeOAuthClientIdPatch.kt:39)
	at app.revanced.patches.syncforreddit.api.patch.ChangeOAuthClientIdPatch.execute(ChangeOAuthClientIdPatch.kt:20)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

**Comment by oSumAtrIX** [comment]
We don't know about unofficial tools. You can use ReVanced Manager and ReVanced CLI to patch the app with the former, by following the error it gives you and the latter, by providing the client id as a patch option

**Comment by warmoans** [comment]
Could someone explain how we get the clientid so it will patch?

**Comment by warmoans** [comment]
Do we have to be logged in for this to work? I prefer using Sync without my account.

**Pull request merged**
