### PR TITLE
feat: add supports for newest YouTube base versions

### PR DESCRIPTION
**Pull request by kazimmt**
Add supports for YouTube v17.37.35, v17.38.35, v17.39.35
All version patched successfully & all patches are also working.

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
What about this: https://github.com/revanced/revanced-patches/pull/698#issuecomment-1265063137? I quickly tried too on the latter versions recently and the patched app was not launching for me.

**Comment by kazimmt** [comment]
> What about this: [#698 (comment)](https://github.com/revanced/revanced-patches/pull/698#issuecomment-1265063137)? I quickly tried too on the latter versions recently and the patched app was not launching for me.

I tried 4 different versions few minutes ago. App working without having any issue. 

Personally send you the full video also while patching.

**Comment by Matty003** [comment]
Do you get this BUG in version 17.39.35 with manager 0.0.32 ?

IMG_20221017_221601

**Comment by kazimmt** [comment]
> Do you get this BUG in version 17.39.35 with manager 0.0.32 ?
> 
> IMG_20221017_221601

No. It works without any issue/error.
I check couple of times cz i find shorts error on 17.40xx
No issues in 17.39

**Comment by Matty003** [comment]
Hmm, that's weird. I got the audio search icon twice on search screen. Will check on manager 33 and 34.

**Comment by kazimmt** [comment]
> Hmm, that's weird. I got the audio search icon twice on search screen. Will check on manager 33 and 34.

**Comment by kazimmt** [comment]
> Hmm, that's weird. I got the audio search icon twice on search screen. Will check on manager 33 and 34.

Screenshot_2022-10-17-22-55-31-483_app revanced android youtube

**Comment by Matty003** [comment]
Hmm, got no problems as you said with manager 0.0.33

**Comment by Issam28** [comment]
> What about this: [#698 (comment)](https://github.com/revanced/revanced-patches/pull/698#issuecomment-1265063137)? I quickly tried too on the latter versions recently and the patched app was not launching for me.

The comment you are referring to is my comment. Back when I tried newer versions I couldn't update from a previous version but it worked when I uninstalled first the previous version. No I'm running V17.39.35 and it's working fine.

**Comment by 8cAyqpVKio** [comment]
We can ignore the YouTube version by using the "--experimental" revanced-cli command.
No reason to upgrade without fixing fingerprints, I think.

**Comment by kazimmt** [comment]
> We can ignore the YouTube version by using the "--experimental" revanced-cli command. No reason to upgrade without fixing fingerprints, I think.

If all patches working without fingerprint change, then why not?
& not everyone building the app using cli!

**Comment by oSumAtrIX** [comment]
Patches need to first pass compilation, then runtime, a patch might succeed at compile time, but fail at runtime.

**Comment by oSumAtrIX** [comment]
Well you claimed that initially too but then had to commit 077052469091ced84e71f4a6a000948b3aa59d15. I will have to review this first.

**Comment by kazimmt** [comment]
> Well you claimed that initially too but then had to commit [0770524](https://github.com/revanced/revanced-patches/commit/077052469091ced84e71f4a6a000948b3aa59d15). I will have to review this first.

Sure. You can review it. 
No problem.

**Comment by ExperiencersInternational** [comment]
> What about this: [#698 (comment)](https://github.com/revanced/revanced-patches/pull/698#issuecomment-1265063137)? I quickly tried too on the latter versions recently and the patched app was not launching for me.

Haven't had issues at all, I'm currently running 17.42.33, the only issues I've had is with video ads not being blocked.

**Comment by oSumAtrIX** [comment]
> Haven't had issues at all, 

> video ads not being blocked.

Seems like there is.

**Comment by oSumAtrIX** [comment]
Due to conflicts and the PR being stale and also needing a proper review, i will close this PR for now.

**Pull request closed without merging**
