### PR TITLE
feat(ID Austria): Remove constraint on any version

### PR DESCRIPTION
**Pull request by 1fexd**

### CODE REVIEW

**Review by oSumAtrIX — COMMENTED** [review]
Maybe the version constraint can be removed?

**Comment by 1fexd** [comment]
Nope, the patch only works with `3.x.x`, not with `2.x.x`

**Comment by oSumAtrIX** [comment]
The idea is to support the latest and future versions

**Comment by 1fexd** [comment]
Is there any way to do a semver check? That would be cool

**Comment by oSumAtrIX** [comment]
The version field is being compared against the versionName which can contain any raw string: 
image

We would need to compare against `versionCode` but then it is not really user friendly.

**Pull request merged**
