### PR TITLE
fix: alignment of copy icon

### PR DESCRIPTION
**Pull request by kazimmt**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Do you have a screenshot of what it looks like? Also drop the chore commit.

**Comment by kazimmt** [comment]
> Do you have a screenshot of what it looks like? Also drop the chore commit.
Screenshot_2023-01-02-15-47-18-840_app rv android youtube-edit
Before


Screenshot_2023-01-02-16-12-30-421_app rv android youtube-edit
This PR

**Comment by oSumAtrIX** [comment]
Probably a more readable set of icons should be used instead of reducing it's size.

**Comment by kazimmt** [comment]
> Probably a more readable set of icons should be used instead of reducing it's size.

But it should align same as download & full screen icon

**Comment by oSumAtrIX** [comment]
For the scope of this PR it's fine, drop the chore commit and we can get it merged.

**Comment by kazimmt** [comment]
> For the scope of this PR it's fine, drop the chore commit and we can get it merged.

The chore coming from nowhere 😑
How can i drop it?

**Comment by rks2000** [comment]
> > Do you have a screenshot of what it looks like? Also drop the chore commit.
> > Screenshot_2023-01-02-15-47-18-840_app rv android youtube-edit
> > Before
> 
> Screenshot_2023-01-02-16-12-30-421_app rv android youtube-edit This PR

Make it like this, so it will much easier to identify 
IMG_20230102_184527

**Pull request closed without merging**
