### PR TITLE
refactor(youtube/general-ads-patch): remove unnecessary patches

### PR DESCRIPTION
**Pull request by OxrxL**
Most probably related to old video-ads patch

### CODE REVIEW

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]
Since only one element is left in the array, it can be removed.

**Comment by OxrxL** [comment]
@oSumAtrIX Can be merged or need others changes?

**Comment by oSumAtrIX** [comment]
This shouldn’t be closed yet.

**Comment by oSumAtrIX** [comment]
Its not stuck, the branch is still available.

**Comment by oSumAtrIX** [comment]
Closing in favour of #1063.

**Pull request closed without merging**
