### PR TITLE
feat: `downloads` patch

### PR DESCRIPTION
**Pull request by oSumAtrIX**

### CODE REVIEW

**Comment by missemily2022** [comment]
@oSumAtrIX When can we expect for this patch to be released?

**Comment by reisxd** [comment]
> @oSumAtrIX When can we expect for this patch to be released?

When its finished.

**Comment by missemily2022** [comment]
@reisxd I had just asked about an estimated time.

**Comment by reisxd** [comment]
> @reisxd I had just asked about an estimated time.

Theres no estimated time, it'll be released when its finished.

**Comment by XRedCubeX** [comment]
Will it be made compatible with youtube music?

**Comment by missemily2022** [comment]
@reisxd Yeah But you could have conversed in a more formal tone.

**Pull request merged**
